### ISSUE TITLE
Download opty-dev with variable h

### ISSUE THREAD

**Issue by Peter230655** [csu-hmc/opty#168] opened 2024-06-21 08:20 UTC
I just saw the latest release.
Could I download it with this command?
![image](https://github.com/csu-hmc/opty/assets/83544146/2670b8de-3634-4218-8090-e86d89e7616b)

**Thanks!**

**Comment by tjstienstra** [comment] 2024-06-21 08:26
That should install opty 1.2.0, which was released on November 28 2023.
If you'd like to install the development version of opty in an environment then you could use `pip install git+https://github.com/csu-hmc/opty.git`

**Comment by Peter230655** [comment] 2024-06-21 08:29
Could I install this in the environment you gave me, where I already have opty installed, or would it destroy things?
Thanks!!

**Comment by tjstienstra** [comment] 2024-06-21 08:41
You should be able to install it in that environment. If you would really like to go all the way you can run both:
```bash
pip install git+https://github.com/sympy/sympy.git
pip install git+https://github.com/csu-hmc/opty.git
```
If you run these two then you should get the development version of both sympy and opty in that environment.

**Comment by Peter230655** [comment] 2024-06-21 08:43
I will do this this evening.
**Thanks a LOT!**

**Comment by Peter230655** [comment] 2024-06-22 07:52
When I run my program with this version of opty, I get the error below.
This did not happen with the old opty 1.2.
It continues to calculate, but the results are much 'worse' than with the old opty.

**Thanks for any advise!**

[Error with opty 1.3.0cr.txt](https://github.com/user-attachments/files/15935727/Error.with.opty.1.3.0cr.txt)

**Comment by moorepants** [comment] 2024-06-22 08:35
Error in attached file:

```
Exception in thread Thread-13 (_readerthread):
Traceback (most recent call last):
  File "c:\Users\Peter\anaconda3\envs\math\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "c:\Users\Peter\anaconda3\envs\math\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Peter\anaconda3\envs\math\Lib\subprocess.py", line 1597, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 419: invalid start byte
Exception in thread Thread-15 (_readerthread):
Traceback (most recent call last):
  File "c:\Users\Peter\anaconda3\envs\math\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "c:\Users\Peter\anaconda3\envs\math\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Peter\anaconda3\envs\math\Lib\subprocess.py", line 1597, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 419: invalid start byte
```

**Comment by Peter230655** [comment] 2024-06-22 10:06
How3 can I open the code myself, so nobody else has to do it?
Thanks!

**Comment by moorepants** [comment] 2024-06-22 12:53
Open what code?

**Comment by Peter230655** [comment] 2024-06-22 14:15
The error seems to be caused by these two commits 
This of course was found by Timo! He patiently guided me!

ebb71f47d069d1b6625b854bc4d0d3a6251ac1e3
b17af906f539dada78672cf703e2b1be6163b3cc

**Comment by moorepants** [comment] 2024-06-22 14:20
You haven't provided enough information for me to understand what you are reporting and how those commits are connected to it. Please provide a minimal reproducible example and open a new issue about it.

**Comment by Peter230655** [comment] 2024-06-22 14:32
My program is quite a monster.
Let me strip it doen an send it to you

**Comment by Peter230655** [comment] 2024-06-22 15:03
The issue is this:
With opty version **1.2.0** all runs like expected
With opty version **1.3.0.dev0** it gives an error, the one given above. It keeps on running, though.
As I cannot attach a jpynb file here I will send by email.

**Comment by Peter230655** [comment] 2024-06-22 15:11
> Open what code?

I meant this: I attached a file containing the error message.
You opened it this file and displayed it.
How can I do this myself?

**Comment by moorepants** [comment] 2024-06-23 05:13
This explains how to format messages in Github text input boxes: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github

Closing this issue, as downloading the development version of opty seems to be resolved.

**Closed by moorepants** 2024-06-23 05:13 UTC
